Rename app
KateF20/taskmanager_django pull request #1
Opened 2023-04-13 13:02 UTC by KateF20

2023-04-13 13:30 UTC, homm requested changes

2023-04-13 13:30 UTC, homm commented on taskmanager/taskeditor/templates/registration/login.html
> +</html>
No newline at the end

2023-04-13 13:30 UTC, homm commented on taskmanager/taskeditor/urls.py
> +    path('', views.index, name='taskeditor'),
Not agree

2023-04-13 13:30 UTC, homm commented on taskmanager/taskeditor/views.py
> +    return render(request, 'main/home.html')
This template is not exist

2023-04-13 13:30 UTC, homm commented on taskmanager/taskeditor/apps.py
Not sure if this file required

2023-04-18 14:11 UTC, KateF20 commented on taskmanager/taskeditor/templates/registration/login.html
> +</html>
done

2023-04-18 15:18 UTC, homm approved these changes

2023-04-18 15:18 UTC, merged